language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "yaroslav-orel-github"
    token:
      secure: "FjyD/+EHEPHHTmlsWoq/YBeNJh+7i0KLpQrbFH7miNibKJy28gUWDzadqxzCEwG3kb9rObMQAN+PazttVLeQbuTwsP+01knf0OBrdOjqnuyIz
               5vg1jiQv8FO34jnMJmihmbLwYBuk+Gr0rg91g8LqnNp3FMryMg5DZOKMHLP/undS3KinZmEsa1qz6TWn0bF8F3HJU5ROEPNoPusyf1e3wuWc04zLUhEhj8Ra
               bRnDjtDWH9MwKziD7VcbLySRGc72XAb9V3K5iySRkRE0cHUHniKSgeiDkI9LBvnDMF8W7Ej0mWwgeYQxnUx5G2Ob+M2QkU44OrNkPH+1XlAJzxcZ4y57MmuM
               wIa6HW/DVWGBo/DBH0li1yNPjQPpSRgqjsxuPQuiT9QY4JjXtFzx2gOU96Yeuclc1mtCq7a0GsD3q9j8UlO0QL8FC/riw1xMme12pUkxId8scvZQTGlCJgBt
               8Z3B9tfTnu6DQa6f5jAieaZOGjKuL6Ri/ntrEiriis/vFILEsy6Mi4rwf29RNJT0MpndZ7KEBWFQzgyuDJpUETeUtsqJZbBiBwMg7YUXKw/IDWY8swCt5FpN
               +GKRNr4qJV4rghomrQPG3H34onamW7bTpuUvB675A9x066QuBrSjIliZMpnQB0jaWpuGNY+fu0dNgAKwWfalFqr5fRnaFk="
jdk:
  - oraclejdk8

before_install:
- chmod +x gradlew

script:
- ./gradlew clean build test sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'