language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "yaroslav-orel-github"
    token:
      secure: "gq+VY0xvK58q0AovMbUkE4dmirxQvon3WHoYjBCwzTN8vE1Qb+P28WDwtalubLCM2mEQHESQZrdAxAOyOxkR2c2zqoTakinVoWys4IueXOAoxxLlK5WcOfV511ZPcMdJ3REpqz/AmUY4bxtc/4U8NutaO9qObK4nuNAr3MoQQNYHPNrna57NVrDBgrI84sLK/L3BUmbMU9LzdMG0/wxYCvRBN6cgdOrSSlZxUsFCzL8QVpfZ62q2wEhGSwVsix/iJyiT6rY2iwzJ+u6amMoMUH/M20TzKgop7
               LbNh4q8/jo+xBPK1T9zKql9UH0KlchZNYx1PGmqfhdSBPxR20Tl/YMeSorqZRZf5Vhf8uSkAfqBUdr94vBBH3S7E1RA+xTVByykALwpMLwIfMCMS7+BLCwMvzYMJGaEhDn1LdoBRA+yxxLcHwuCiTD9VJtxIDH5QIamzbMB6/874nVGySNQJNf5HNo8LA4EpIn9SsSVX4rTKQJvKRLiQP3PLga6bUi7lQ0hVuWFFkku1DHUGzJ9mV8L/8uSGUciPP5y2/KT19IE22Q/c6y+qbICQnop3A0Alt2KMQaFgoJIN
               IHKhXyDg0GOROgoNEvKYBcZzGLe1hg2/4osh0amUcNsNSr/f6VdFZinpjaT3Ap/v0LrdFrRKIH0mG3OnEbngkcu4iW+SDc="
jdk:
  - oraclejdk8

before_install:
- chmod +x gradlew

script:
- ./gradlew clean build test sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'